// components/ContentSection.tsx
import React from "react";
import { useRouter } from "next/router";
import de from "../../dictionaries/de.json";
import ru from "../../dictionaries/ru.json";

const ContentSection: React.FC = () => {
  const router = useRouter();
  const { locale } = router;
  const t = locale === "de" ? de : ru;

  return (
    <>
      <section className="bg-gray-100 py-8">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
            <div>
              <h2 className="mb-4 text-2xl font-bold">
                {t.jetztMitgliedWerden}
              </h2>
              <p className="mb-4 text-lg">{t.mitgliedWerdenDescription}</p>
              <p className="mb-4 text-lg">{t.abenteurerGesucht}</p>
              <p className="mb-4 text-lg">{t.wirFreuenUns}</p>
              <p className="mb-4 text-lg">{t.kontaktEmail}</p>
              <a href="#" className="text-lg text-blue-500 underline">
                {t.mitgliedsantragLink}
              </a>
            </div>
            <div>
              <iframe
                width="100%"
                height="315"
                src="https://www.youtube.com/embed/FEmZHsn2xr0"
                title="OstpreussenTV"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              ></iframe>
              <p className="mt-4 text-lg">{t.mehrInformationen}</p>
              <a
                href="http://www.youtube.com/user/OstpreussenTV"
                className="text-lg text-blue-500 underline"
              >
                {t.youtubeLink}
              </a>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-gray-200 py-10">
      <div className="container mx-auto px-4">
        <h2 className="mb-6 text-3xl font-bold">{t.vorstellungsgespraech}</h2>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
          <div className="rounded-lg bg-white p-6 shadow-lg">
            <h3 className="mb-4 text-xl font-bold">{t.landschaftErleben}</h3>
            <p>{t.landschaftErlebenDescription}</p>
          </div>
          <div className="rounded-lg bg-white p-6 shadow-lg">
            <h3 className="mb-4 text-xl font-bold">{t.geschichteEntdecken}</h3>
            <p>{t.geschichteEntdeckenDescription}</p>
          </div>
          <div className="rounded-lg bg-white p-6 shadow-lg">
            <h3 className="mb-4 text-xl font-bold">{t.gemeinschaftErfahren}</h3>
            <p>{t.gemeinschaftErfahrenDescription}</p>
          </div>
        </div>
      </div>
    </section>
    </>
  );
};

export default ContentSection;

// import { signIn, signOut, useSession } from "next-auth/react";
// import Head from "next/head";
// import Link from "next/link";

// import { api } from "@/components/utils/api";

// export default function Home() {
//   const hello = api.example.hello.useQuery({ text: "from tRPC" });

//   return (
//     <>
//       <Head>
//         <title>Create T3 App</title>
//         <meta name="description" content="Generated by create-t3-app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
//         <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
//           <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
//             Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
//           </h1>
//           <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
//             <Link
//               className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
//               href="https://create.t3.gg/en/usage/first-steps"
//               target="_blank"
//             >
//               <h3 className="text-2xl font-bold">First Steps →</h3>
//               <div className="text-lg">
//                 Just the basics - Everything you need to know to set up your
//                 database and authentication.
//               </div>
//             </Link>
//             <Link
//               className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
//               href="https://create.t3.gg/en/introduction"
//               target="_blank"
//             >
//               <h3 className="text-2xl font-bold">Documentation →</h3>
//               <div className="text-lg">
//                 Learn more about Create T3 App, the libraries it uses, and how
//                 to deploy it.
//               </div>
//             </Link>
//           </div>
//           <div className="flex flex-col items-center gap-2">
//             <p className="text-2xl text-white">
//               {hello.data ? hello.data.greeting : "Loading tRPC query..."}
//             </p>
//             <AuthShowcase />
//           </div>
//         </div>
//       </main>
//     </>
//   );
// }

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
